version: '3'
services:
  mongo-teppeti:
    image: mongo:4
    container_name: mongo-teppeti
    ports:
      - '27017:27017'
    volumes:
      - ./src/database/scripts:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    networks:
      - teppeti
    command: --replSet rs2
networks:
  teppeti:
volumes:
  mongo_data:
